// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package uhost

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source providers a list of UHost instance resources according to their availability zone, instance ID and tag.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-ucloud/sdk/go/ucloud/uhost"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		opt0 := "cn-bj2-02"
// 		example, err := uhost.LookupInstance(ctx, &uhost.LookupInstanceArgs{
// 			AvailabilityZone: &opt0,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("first", example.Instances[0].Id)
// 		return nil
// 	})
// }
// ```
func LookupInstance(ctx *pulumi.Context, args *LookupInstanceArgs, opts ...pulumi.InvokeOption) (*LookupInstanceResult, error) {
	var rv LookupInstanceResult
	err := ctx.Invoke("ucloud:uhost/getInstance:getInstance", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInstance.
type LookupInstanceArgs struct {
	// Availability zone where instances are located. Such as: "cn-bj2-02". You may refer to [list of availability zone](https://docs.ucloud.cn/api/summary/regionlist)
	AvailabilityZone *string `pulumi:"availabilityZone"`
	// A list of instance IDs, all the instances belongs to the defined region will be retrieved if this argument is `[]`.
	Ids []string `pulumi:"ids"`
	// A regex string to filter resulting instances by name.
	NameRegex  *string `pulumi:"nameRegex"`
	OutputFile *string `pulumi:"outputFile"`
	// A tag assigned to instance.
	Tag *string `pulumi:"tag"`
}

// A collection of values returned by getInstance.
type LookupInstanceResult struct {
	// Availability zone where instances are located.
	AvailabilityZone *string `pulumi:"availabilityZone"`
	// The provider-assigned unique ID for this managed resource.
	Id  string   `pulumi:"id"`
	Ids []string `pulumi:"ids"`
	// It is a nested type. instances documented below.
	Instances  []GetInstanceInstance `pulumi:"instances"`
	NameRegex  *string               `pulumi:"nameRegex"`
	OutputFile *string               `pulumi:"outputFile"`
	// A tag assigned to the instance.
	Tag *string `pulumi:"tag"`
	// Total number of instances that satisfy the condition.
	TotalCount int `pulumi:"totalCount"`
}
