# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetProjectProjectResult',
    'GetZoneZoneResult',
]

@pulumi.output_type
class GetProjectProjectResult(dict):
    def __init__(__self__, *,
                 create_time: str,
                 id: str,
                 member_count: int,
                 name: str,
                 parent_id: str,
                 parent_name: str,
                 resource_count: int):
        """
        :param str create_time: The time of creation for instance, formatted in RFC3339 time string.
        :param str id: The ID of project defined.
        :param int member_count: The number of members belongs to the defined project.
        :param str name: The name of the defined project.
        :param str parent_id: The ID of the parent project where the sub project belongs to.
        :param str parent_name: The name of the parent project where the sub project belongs to.
        :param int resource_count: The number of the resounce instance belong/s to the defined project.
        """
        pulumi.set(__self__, "create_time", create_time)
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "member_count", member_count)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "parent_id", parent_id)
        pulumi.set(__self__, "parent_name", parent_name)
        pulumi.set(__self__, "resource_count", resource_count)

    @property
    @pulumi.getter(name="createTime")
    def create_time(self) -> str:
        """
        The time of creation for instance, formatted in RFC3339 time string.
        """
        return pulumi.get(self, "create_time")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The ID of project defined.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="memberCount")
    def member_count(self) -> int:
        """
        The number of members belongs to the defined project.
        """
        return pulumi.get(self, "member_count")

    @property
    @pulumi.getter
    def name(self) -> str:
        """
        The name of the defined project.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> str:
        """
        The ID of the parent project where the sub project belongs to.
        """
        return pulumi.get(self, "parent_id")

    @property
    @pulumi.getter(name="parentName")
    def parent_name(self) -> str:
        """
        The name of the parent project where the sub project belongs to.
        """
        return pulumi.get(self, "parent_name")

    @property
    @pulumi.getter(name="resourceCount")
    def resource_count(self) -> int:
        """
        The number of the resounce instance belong/s to the defined project.
        """
        return pulumi.get(self, "resource_count")


@pulumi.output_type
class GetZoneZoneResult(dict):
    def __init__(__self__, *,
                 id: str):
        """
        :param str id: The ID of availability zone.
        """
        pulumi.set(__self__, "id", id)

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The ID of availability zone.
        """
        return pulumi.get(self, "id")


