// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * This data source provides a list of database instance resources according to their database instance ID and name.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ucloud from "@pulumi/ucloud";
 *
 * const example = ucloud.udb.getDBInstance({});
 * export const first = example.then(example => example.dbInstances[0].id);
 * ```
 */
export function getDBInstance(args?: GetDBInstanceArgs, opts?: pulumi.InvokeOptions): Promise<GetDBInstanceResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ucloud:udb/getDBInstance:getDBInstance", {
        "availabilityZone": args.availabilityZone,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);
}

/**
 * A collection of arguments for invoking getDBInstance.
 */
export interface GetDBInstanceArgs {
    /**
     * Availability zone where database instances are located. Such as: "cn-bj2-02". You may refer to [list of availability zone](https://docs.ucloud.cn/api/summary/regionlist)
     */
    availabilityZone?: string;
    /**
     * A list of database instance IDs, all the database instances belong to this region will be retrieved if the ID is `[]`.
     */
    ids?: string[];
    /**
     * A regex string to filter resulting database instances by name.
     */
    nameRegex?: string;
    outputFile?: string;
}

/**
 * A collection of values returned by getDBInstance.
 */
export interface GetDBInstanceResult {
    /**
     * Availability zone where database instance is located.
     */
    readonly availabilityZone?: string;
    /**
     * It is a nested type which documented below.
     */
    readonly dbInstances: outputs.udb.GetDBInstanceDbInstance[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids: string[];
    readonly nameRegex?: string;
    readonly outputFile?: string;
    /**
     * Total number of database instances that satisfy the condition.
     */
    readonly totalCount: number;
}
