// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package udb

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides a list of database instance resources according to their database instance ID and name.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-ucloud/sdk/go/ucloud/udb"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		example, err := udb.LookupDBInstance(ctx, nil, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("first", example.DbInstances[0].Id)
// 		return nil
// 	})
// }
// ```
func LookupDBInstance(ctx *pulumi.Context, args *LookupDBInstanceArgs, opts ...pulumi.InvokeOption) (*LookupDBInstanceResult, error) {
	var rv LookupDBInstanceResult
	err := ctx.Invoke("ucloud:udb/getDBInstance:getDBInstance", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDBInstance.
type LookupDBInstanceArgs struct {
	// Availability zone where database instances are located. Such as: "cn-bj2-02". You may refer to [list of availability zone](https://docs.ucloud.cn/api/summary/regionlist)
	AvailabilityZone *string `pulumi:"availabilityZone"`
	// A list of database instance IDs, all the database instances belong to this region will be retrieved if the ID is `[]`.
	Ids []string `pulumi:"ids"`
	// A regex string to filter resulting database instances by name.
	NameRegex  *string `pulumi:"nameRegex"`
	OutputFile *string `pulumi:"outputFile"`
}

// A collection of values returned by getDBInstance.
type LookupDBInstanceResult struct {
	// Availability zone where database instance is located.
	AvailabilityZone *string `pulumi:"availabilityZone"`
	// It is a nested type which documented below.
	DbInstances []GetDBInstanceDbInstance `pulumi:"dbInstances"`
	// The provider-assigned unique ID for this managed resource.
	Id         string   `pulumi:"id"`
	Ids        []string `pulumi:"ids"`
	NameRegex  *string  `pulumi:"nameRegex"`
	OutputFile *string  `pulumi:"outputFile"`
	// Total number of database instances that satisfy the condition.
	TotalCount int `pulumi:"totalCount"`
}
