// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ucloud.Uaccount.Outputs
{

    [OutputType]
    public sealed class GetProjectProjectResult
    {
        /// <summary>
        /// The time of creation for instance, formatted in RFC3339 time string.
        /// </summary>
        public readonly string CreateTime;
        /// <summary>
        /// The ID of project defined.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The number of members belongs to the defined project.
        /// </summary>
        public readonly int MemberCount;
        /// <summary>
        /// The name of the defined project.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ID of the parent project where the sub project belongs to.
        /// </summary>
        public readonly string ParentId;
        /// <summary>
        /// The name of the parent project where the sub project belongs to.
        /// </summary>
        public readonly string ParentName;
        /// <summary>
        /// The number of the resounce instance belong/s to the defined project.
        /// </summary>
        public readonly int ResourceCount;

        [OutputConstructor]
        private GetProjectProjectResult(
            string createTime,

            string id,

            int memberCount,

            string name,

            string parentId,

            string parentName,

            int resourceCount)
        {
            CreateTime = createTime;
            Id = id;
            MemberCount = memberCount;
            Name = name;
            ParentId = parentId;
            ParentName = parentName;
            ResourceCount = resourceCount;
        }
    }
}
