// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ucloud.Ipsecvpn.Outputs
{

    [OutputType]
    public sealed class VPNConnectionIkeConfig
    {
        /// <summary>
        /// The authentication algorithm of IPSec negotiation. Possible values: `sha1`, `md5`. (Default: `sha1`)
        /// </summary>
        public readonly string? AuthenticationAlgorithm;
        /// <summary>
        /// The Diffie-Hellman group used by IKE negotiation. Possible values: `1`, `2`, `5`, `14`, `15`, `16`. (Default:`15`)
        /// </summary>
        public readonly string? DhGroup;
        /// <summary>
        /// The encryption algorithm of IPSec negotiation. Possible values: `aes128`, `aes192`, `aes256`, `aes512`, `3des`. (Default: `aes128`).
        /// </summary>
        public readonly string? EncryptionAlgorithm;
        /// <summary>
        /// The negotiation exchange mode of IKE V1 of VPN gateway. Possible values: `main` (main mode), `aggressive` (aggressive mode). (Default: `main`)
        /// </summary>
        public readonly string? ExchangeMode;
        /// <summary>
        /// The version of the IKE protocol which only be supported IKE V1 protocol at present. Possible values: ikev1. (Default: ikev1)
        /// </summary>
        public readonly string? IkeVersion;
        /// <summary>
        /// The identification of the VPN gateway.
        /// </summary>
        public readonly string? LocalId;
        /// <summary>
        /// The key used for authentication between the VPN gateway and the Customer gateway which contains 1-128 characters and only support English, numbers and special characters: `!@#$%^&amp;*()_+-=[]:,./'~`.
        /// </summary>
        public readonly string PreSharedKey;
        /// <summary>
        /// The identification of the Customer gateway.
        /// </summary>
        public readonly string? RemoteId;
        /// <summary>
        /// The Security Association lifecycle as the result of IPSec negotiation. Unit: second. Range: 1200-604800. (Default: `3600`)
        /// </summary>
        public readonly int? SaLifeTime;

        [OutputConstructor]
        private VPNConnectionIkeConfig(
            string? authenticationAlgorithm,

            string? dhGroup,

            string? encryptionAlgorithm,

            string? exchangeMode,

            string? ikeVersion,

            string? localId,

            string preSharedKey,

            string? remoteId,

            int? saLifeTime)
        {
            AuthenticationAlgorithm = authenticationAlgorithm;
            DhGroup = dhGroup;
            EncryptionAlgorithm = encryptionAlgorithm;
            ExchangeMode = exchangeMode;
            IkeVersion = ikeVersion;
            LocalId = localId;
            PreSharedKey = preSharedKey;
            RemoteId = remoteId;
            SaLifeTime = saLifeTime;
        }
    }
}
