// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * This data source provides a list of Load Balancer resources according to their Load Balancer ID, VPC ID and Subnet ID.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ucloud from "@pulumi/ucloud";
 *
 * const example = ucloud.ulb.getLB({});
 * export const first = example.then(example => example.lbs[0].id);
 * ```
 */
export function getLB(args?: GetLBArgs, opts?: pulumi.InvokeOptions): Promise<GetLBResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ucloud:ulb/getLB:getLB", {
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
        "subnetId": args.subnetId,
        "vpcId": args.vpcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getLB.
 */
export interface GetLBArgs {
    /**
     * A list of Load Balancer IDs, all the LBs belong to this region will be retrieved if the ID is `[]`.
     */
    ids?: string[];
    /**
     * A regex string to filter resulting lbs by name.
     */
    nameRegex?: string;
    outputFile?: string;
    /**
     * The ID of subnet that intrant load balancer belongs to.
     */
    subnetId?: string;
    /**
     * The ID of the VPC linked to the Load Balancers.
     */
    vpcId?: string;
}

/**
 * A collection of values returned by getLB.
 */
export interface GetLBResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids: string[];
    /**
     * It is a nested type which documented below.
     */
    readonly lbs: outputs.ulb.GetLBLb[];
    readonly nameRegex?: string;
    readonly outputFile?: string;
    /**
     * (Optional) The ID of subnet that intrant load balancer belongs to.
     */
    readonly subnetId: string;
    /**
     * Total number of Load Balancers that satisfy the condition.
     */
    readonly totalCount: number;
    /**
     * The ID of the VPC linked to the Load Balancers.
     */
    readonly vpcId: string;
}
