# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from typing import Union
from .. import utilities, tables

class Vpc(pulumi.CustomResource):
    cidr_blocks: pulumi.Output[list]
    """
    The CIDR blocks of VPC.
    """
    create_time: pulumi.Output[str]
    """
    The time of creation for VPC, formatted in RFC3339 time string.
    """
    name: pulumi.Output[str]
    network_infos: pulumi.Output[list]
    """
    It is a nested type which documented below.
    
      * `cidr_block` (`str`) - The CIDR block of the VPC.
    """
    remark: pulumi.Output[str]
    """
    The remarks of the VPC. (Default: `""`).
    """
    tag: pulumi.Output[str]
    """
    A tag assigned to VPC, which contains at most 63 characters and only support Chinese, English, numbers, '-', '_', and '.'. If it is not filled in or a empty string is filled in, then default tag will be assigned. (Default: `Default`).
    """
    update_time: pulumi.Output[str]
    """
    The time whenever there is a change made to VPC, formatted in RFC3339 time string.
    """
    def __init__(__self__, resource_name, opts=None, cidr_blocks=None, name=None, remark=None, tag=None, __props__=None, __name__=None, __opts__=None):
        """
        Provides a VPC resource.
        
        > **Note**  The network segment can only be created or deleted, can not perform both of them at the same time.
        
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[list] cidr_blocks: The CIDR blocks of VPC.
        :param pulumi.Input[str] remark: The remarks of the VPC. (Default: `""`).
        :param pulumi.Input[str] tag: A tag assigned to VPC, which contains at most 63 characters and only support Chinese, English, numbers, '-', '_', and '.'. If it is not filled in or a empty string is filled in, then default tag will be assigned. (Default: `Default`).

        > This content is derived from https://github.com/terraform-providers/terraform-provider-ucloud/blob/master/website/docs/r/vpc.html.markdown.
        """
        if __name__ is not None:
            warnings.warn("explicit use of __name__ is deprecated", DeprecationWarning)
            resource_name = __name__
        if __opts__ is not None:
            warnings.warn("explicit use of __opts__ is deprecated, use 'opts' instead", DeprecationWarning)
            opts = __opts__
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = dict()

            if cidr_blocks is None:
                raise TypeError("Missing required property 'cidr_blocks'")
            __props__['cidr_blocks'] = cidr_blocks
            __props__['name'] = name
            __props__['remark'] = remark
            __props__['tag'] = tag
            __props__['create_time'] = None
            __props__['network_infos'] = None
            __props__['update_time'] = None
        super(Vpc, __self__).__init__(
            'ucloud:vpc/vpc:Vpc',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name, id, opts=None, cidr_blocks=None, create_time=None, name=None, network_infos=None, remark=None, tag=None, update_time=None):
        """
        Get an existing Vpc resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.
        
        :param str resource_name: The unique name of the resulting resource.
        :param str id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[list] cidr_blocks: The CIDR blocks of VPC.
        :param pulumi.Input[str] create_time: The time of creation for VPC, formatted in RFC3339 time string.
        :param pulumi.Input[list] network_infos: It is a nested type which documented below.
        :param pulumi.Input[str] remark: The remarks of the VPC. (Default: `""`).
        :param pulumi.Input[str] tag: A tag assigned to VPC, which contains at most 63 characters and only support Chinese, English, numbers, '-', '_', and '.'. If it is not filled in or a empty string is filled in, then default tag will be assigned. (Default: `Default`).
        :param pulumi.Input[str] update_time: The time whenever there is a change made to VPC, formatted in RFC3339 time string.
        
        The **network_infos** object supports the following:
        
          * `cidr_block` (`pulumi.Input[str]`) - The CIDR block of the VPC.

        > This content is derived from https://github.com/terraform-providers/terraform-provider-ucloud/blob/master/website/docs/r/vpc.html.markdown.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = dict()
        __props__["cidr_blocks"] = cidr_blocks
        __props__["create_time"] = create_time
        __props__["name"] = name
        __props__["network_infos"] = network_infos
        __props__["remark"] = remark
        __props__["tag"] = tag
        __props__["update_time"] = update_time
        return Vpc(resource_name, opts=opts, __props__=__props__)
    def translate_output_property(self, prop):
        return tables._CAMEL_TO_SNAKE_CASE_TABLE.get(prop) or prop

    def translate_input_property(self, prop):
        return tables._SNAKE_TO_CAMEL_CASE_TABLE.get(prop) or prop

