// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package ulb

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides a list of Load Balancer Rule resources according to their Load Balancer Rule ID.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-ucloud/sdk/go/ucloud/ulb"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		example, err := ulb.GetLBRules(ctx, &ulb.GetLBRulesArgs{
// 			LoadBalancerId: "ulb-xxx",
// 			ListenerId:     "vserver-xxx",
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("first", example.LbRules[0].Id)
// 		return nil
// 	})
// }
// ```
func GetLBRules(ctx *pulumi.Context, args *GetLBRulesArgs, opts ...pulumi.InvokeOption) (*GetLBRulesResult, error) {
	var rv GetLBRulesResult
	err := ctx.Invoke("ucloud:ulb/getLBRules:getLBRules", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLBRules.
type GetLBRulesArgs struct {
	// A list of LB Rule IDs, all the LB Rules belong to the Load Balancer listener will be retrieved if the ID is `[]`.
	Ids []string `pulumi:"ids"`
	// The ID of a listener server.
	ListenerId string `pulumi:"listenerId"`
	// The ID of a load balancer.
	LoadBalancerId string  `pulumi:"loadBalancerId"`
	OutputFile     *string `pulumi:"outputFile"`
}

// A collection of values returned by getLBRules.
type GetLBRulesResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id  string   `pulumi:"id"`
	Ids []string `pulumi:"ids"`
	// It is a nested type which documented below.
	LbRules        []GetLBRulesLbRule `pulumi:"lbRules"`
	ListenerId     string             `pulumi:"listenerId"`
	LoadBalancerId string             `pulumi:"loadBalancerId"`
	OutputFile     *string            `pulumi:"outputFile"`
	// Total number of LB Rules that satisfy the condition.
	TotalCount int `pulumi:"totalCount"`
}
