// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package ulb

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// This data source provides a list of Load Balancer resources according to their Load Balancer ID, VPC ID and Subnet ID.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-ucloud/blob/master/website/docs/d/lbs.html.markdown.
func LookupLbs(ctx *pulumi.Context, args *LookupLbsArgs, opts ...pulumi.InvokeOption) (*LookupLbsResult, error) {
	var rv LookupLbsResult
	err := ctx.Invoke("ucloud:ulb/lookupLbs:lookupLbs", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking lookupLbs.
type LookupLbsArgs struct {
	// A list of Load Balancer IDs, all the LBs belong to this region will be retrieved if the ID is `""`.
	Ids []string `pulumi:"ids"`
	// A regex string to filter resulting lbs by name.
	NameRegex  *string `pulumi:"nameRegex"`
	OutputFile *string `pulumi:"outputFile"`
	// The ID of subnet that intrant load balancer belongs to.
	SubnetId *string `pulumi:"subnetId"`
	// The ID of the VPC linked to the Load Balancers.
	VpcId *string `pulumi:"vpcId"`
}

// A collection of values returned by lookupLbs.
type LookupLbsResult struct {
	// id is the provider-assigned unique ID for this managed resource.
	Id  string   `pulumi:"id"`
	Ids []string `pulumi:"ids"`
	// It is a nested type which documented below.
	Lbs        []LookupLbsLb `pulumi:"lbs"`
	NameRegex  *string       `pulumi:"nameRegex"`
	OutputFile *string       `pulumi:"outputFile"`
	// (Optional) The ID of subnet that intrant load balancer belongs to.
	SubnetId string `pulumi:"subnetId"`
	// Total number of Load Balancers that satisfy the condition.
	TotalCount int `pulumi:"totalCount"`
	// The ID of the VPC linked to the Load Balancers.
	VpcId string `pulumi:"vpcId"`
}
