// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ucloud.Ipsecvpn.Inputs
{

    public sealed class VPNConnectionIpsecConfigGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The authentication algorithm of IPSec negotiation. Possible values: `sha1`, `md5`. (Default: `sha1`)
        /// </summary>
        [Input("authenticationAlgorithm")]
        public Input<string>? AuthenticationAlgorithm { get; set; }

        /// <summary>
        /// The encryption algorithm of IPSec negotiation. Possible values: `aes128`, `aes192`, `aes256`, `aes512`, `3des`. (Default: `aes128`).
        /// </summary>
        [Input("encryptionAlgorithm")]
        public Input<string>? EncryptionAlgorithm { get; set; }

        [Input("localSubnetIds", required: true)]
        private InputList<string>? _localSubnetIds;

        /// <summary>
        /// The id list of Local subnet.
        /// </summary>
        public InputList<string> LocalSubnetIds
        {
            get => _localSubnetIds ?? (_localSubnetIds = new InputList<string>());
            set => _localSubnetIds = value;
        }

        /// <summary>
        /// Whether the PFS of IPSec negotiation is on or off, `disable` as off, The Diffie-Hellman group as open.  Possible values: `disable`, `1`, `2`, `5`, `14`, `15`, `16`. (Default:`disable`)
        /// </summary>
        [Input("pfsDhGroup")]
        public Input<string>? PfsDhGroup { get; set; }

        /// <summary>
        /// The security protocol of IPSec negotiation. Possible values: `esp`, `ah`. (Default:`esp`)
        /// </summary>
        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        [Input("remoteSubnets", required: true)]
        private InputList<string>? _remoteSubnets;

        /// <summary>
        /// The ip address list of remote subnet.
        /// </summary>
        public InputList<string> RemoteSubnets
        {
            get => _remoteSubnets ?? (_remoteSubnets = new InputList<string>());
            set => _remoteSubnets = value;
        }

        /// <summary>
        /// The Security Association lifecycle as the result of IPSec negotiation. Unit: second. Range: 1200-604800. (Default: `3600`)
        /// </summary>
        [Input("saLifeTime")]
        public Input<int>? SaLifeTime { get; set; }

        /// <summary>
        /// The Security Association lifecycle in bytes as the result of IPSec negotiation. Unit: second. Range: 1200-604800. (Default: `3600`)
        /// </summary>
        [Input("saLifeTimeBytes")]
        public Input<int>? SaLifeTimeBytes { get; set; }

        public VPNConnectionIpsecConfigGetArgs()
        {
        }
    }
}
