// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

/**
 * This data source providers a list of UHost instance resources according to their availability zone, instance ID and tag.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ucloud from "@pulumi/ucloud";
 *
 * const example = ucloud.uhost.getInstance({
 *     availabilityZone: "cn-bj2-02",
 * });
 * export const first = example.then(example => example.instances[0].id);
 * ```
 */
export function getInstance(args?: GetInstanceArgs, opts?: pulumi.InvokeOptions): Promise<GetInstanceResult> {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("ucloud:uhost/getInstance:getInstance", {
        "availabilityZone": args.availabilityZone,
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
        "tag": args.tag,
    }, opts);
}

/**
 * A collection of arguments for invoking getInstance.
 */
export interface GetInstanceArgs {
    /**
     * Availability zone where instances are located. Such as: "cn-bj2-02". You may refer to [list of availability zone](https://docs.ucloud.cn/api/summary/regionlist)
     */
    availabilityZone?: string;
    /**
     * A list of instance IDs, all the instances belongs to the defined region will be retrieved if this argument is `[]`.
     */
    ids?: string[];
    /**
     * A regex string to filter resulting instances by name.
     */
    nameRegex?: string;
    outputFile?: string;
    /**
     * A tag assigned to instance.
     */
    tag?: string;
}

/**
 * A collection of values returned by getInstance.
 */
export interface GetInstanceResult {
    /**
     * Availability zone where instances are located.
     */
    readonly availabilityZone?: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly ids: string[];
    /**
     * It is a nested type. instances documented below.
     */
    readonly instances: outputs.uhost.GetInstanceInstance[];
    readonly nameRegex?: string;
    readonly outputFile?: string;
    /**
     * A tag assigned to the instance.
     */
    readonly tag?: string;
    /**
     * Total number of instances that satisfy the condition.
     */
    readonly totalCount: number;
}
