// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Provides an Isolation Group resource. The Isolation Group is a logical group of UHost instance, which ensure that each UHost instance within a group is on a different physical machine. Up to seven UHost instance can be added per isolation group in a single availability_zone.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as ucloud from "@pulumi/ucloud";
 *
 * const foo = new ucloud.uhost.IsolationGroup("foo", {
 *     remark: "test",
 * });
 * ```
 *
 * ## Import
 *
 * Isolation Group can be imported using the `id`, e.g.
 *
 * ```sh
 *  $ pulumi import ucloud:uhost/isolationGroup:IsolationGroup example ig-abc123456
 * ```
 */
export class IsolationGroup extends pulumi.CustomResource {
    /**
     * Get an existing IsolationGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IsolationGroupState, opts?: pulumi.CustomResourceOptions): IsolationGroup {
        return new IsolationGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'ucloud:uhost/isolationGroup:IsolationGroup';

    /**
     * Returns true if the given object is an instance of IsolationGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IsolationGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IsolationGroup.__pulumiType;
    }

    public readonly name!: pulumi.Output<string>;
    /**
     * The remarks of the isolation group. (Default: `""`).
     */
    public readonly remark!: pulumi.Output<string>;

    /**
     * Create a IsolationGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IsolationGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IsolationGroupArgs | IsolationGroupState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IsolationGroupState | undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["remark"] = state ? state.remark : undefined;
        } else {
            const args = argsOrState as IsolationGroupArgs | undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["remark"] = args ? args.remark : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(IsolationGroup.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IsolationGroup resources.
 */
export interface IsolationGroupState {
    name?: pulumi.Input<string>;
    /**
     * The remarks of the isolation group. (Default: `""`).
     */
    remark?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IsolationGroup resource.
 */
export interface IsolationGroupArgs {
    name?: pulumi.Input<string>;
    /**
     * The remarks of the isolation group. (Default: `""`).
     */
    remark?: pulumi.Input<string>;
}
