// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package unet

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides a list of EIP resources (Elastic IP address) according to their EIP ID.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-ucloud/sdk/go/ucloud/unet"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		example, err := unet.LookupEIP(ctx, nil, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("first", example.Eips[0].IpSets[0].Ip)
// 		return nil
// 	})
// }
// ```
func LookupEIP(ctx *pulumi.Context, args *LookupEIPArgs, opts ...pulumi.InvokeOption) (*LookupEIPResult, error) {
	var rv LookupEIPResult
	err := ctx.Invoke("ucloud:unet/getEIP:getEIP", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getEIP.
type LookupEIPArgs struct {
	// A list of Elastic IP IDs, all the EIPs belong to this region will be retrieved if the ID is `[]`.
	Ids []string `pulumi:"ids"`
	// A regex string to filter resulting eips by name.
	NameRegex  *string `pulumi:"nameRegex"`
	OutputFile *string `pulumi:"outputFile"`
}

// A collection of values returned by getEIP.
type LookupEIPResult struct {
	// It is a nested type which documented below.
	Eips []GetEIPEip `pulumi:"eips"`
	// The provider-assigned unique ID for this managed resource.
	Id         string   `pulumi:"id"`
	Ids        []string `pulumi:"ids"`
	NameRegex  *string  `pulumi:"nameRegex"`
	OutputFile *string  `pulumi:"outputFile"`
	// Total number of Elastic IPs that satisfy the condition.
	TotalCount int `pulumi:"totalCount"`
}
