// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package vpc

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// This data source provides a list of VPC resources according to their VPC ID, name.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-ucloud/sdk/go/ucloud/vpc"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		example, err := vpc.LookupVPC(ctx, nil, nil)
// 		if err != nil {
// 			return err
// 		}
// 		ctx.Export("first", example.Vpcs[0].Id)
// 		return nil
// 	})
// }
// ```
func LookupVPC(ctx *pulumi.Context, args *LookupVPCArgs, opts ...pulumi.InvokeOption) (*LookupVPCResult, error) {
	var rv LookupVPCResult
	err := ctx.Invoke("ucloud:vpc/getVPC:getVPC", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVPC.
type LookupVPCArgs struct {
	// A list of VPC IDs, all the VPC resources belong to this region will be retrieved if the ID is `[]`.
	Ids []string `pulumi:"ids"`
	// A regex string to filter resulting VPC resources by name.
	NameRegex  *string `pulumi:"nameRegex"`
	OutputFile *string `pulumi:"outputFile"`
	// A tag assigned to VPC.
	Tag *string `pulumi:"tag"`
}

// A collection of values returned by getVPC.
type LookupVPCResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id         string   `pulumi:"id"`
	Ids        []string `pulumi:"ids"`
	NameRegex  *string  `pulumi:"nameRegex"`
	OutputFile *string  `pulumi:"outputFile"`
	// A tag assigned to VPC.
	Tag *string `pulumi:"tag"`
	// Total number of VPC resources that satisfy the condition.
	TotalCount int `pulumi:"totalCount"`
	// It is a nested type which documented below.
	Vpcs []GetVPCVpc `pulumi:"vpcs"`
}
