// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package vpc

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

// This data source provides a list of Subnet resources according to their Subnet ID, name and the VPC they belong to.
//
// > This content is derived from https://github.com/terraform-providers/terraform-provider-ucloud/blob/master/website/docs/d/subnets.html.markdown.
func LookupSubnets(ctx *pulumi.Context, args *LookupSubnetsArgs, opts ...pulumi.InvokeOption) (*LookupSubnetsResult, error) {
	var rv LookupSubnetsResult
	err := ctx.Invoke("ucloud:vpc/lookupSubnets:lookupSubnets", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking lookupSubnets.
type LookupSubnetsArgs struct {
	// A list of Subnet IDs, all the Subnet resources belong to this region will be retrieved if the ID is `""`.
	Ids []string `pulumi:"ids"`
	// A regex string to filter resulting Subnet resources by name.
	NameRegex  *string `pulumi:"nameRegex"`
	OutputFile *string `pulumi:"outputFile"`
	Tag        *string `pulumi:"tag"`
	// The id of the VPC that the desired Subnet belongs to.
	VpcId *string `pulumi:"vpcId"`
}

// A collection of values returned by lookupSubnets.
type LookupSubnetsResult struct {
	// id is the provider-assigned unique ID for this managed resource.
	Id         string   `pulumi:"id"`
	Ids        []string `pulumi:"ids"`
	NameRegex  *string  `pulumi:"nameRegex"`
	OutputFile *string  `pulumi:"outputFile"`
	// It is a nested type which documented below.
	Subnets []LookupSubnetsSubnet `pulumi:"subnets"`
	// A tag assigned to Subnet.
	Tag *string `pulumi:"tag"`
	// Total number of Subnet resources that satisfy the condition.
	TotalCount int     `pulumi:"totalCount"`
	VpcId      *string `pulumi:"vpcId"`
}
