// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function lookupNatGateways(args?: LookupNatGatewaysArgs, opts?: pulumi.InvokeOptions): Promise<LookupNatGatewaysResult> & LookupNatGatewaysResult {
    args = args || {};
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    const promise: Promise<LookupNatGatewaysResult> = pulumi.runtime.invoke("ucloud:vpc/lookupNatGateways:lookupNatGateways", {
        "ids": args.ids,
        "nameRegex": args.nameRegex,
        "outputFile": args.outputFile,
    }, opts);

    return pulumi.utils.liftProperties(promise, opts);
}

/**
 * A collection of arguments for invoking lookupNatGateways.
 */
export interface LookupNatGatewaysArgs {
    readonly ids?: string[];
    readonly nameRegex?: string;
    readonly outputFile?: string;
}

/**
 * A collection of values returned by lookupNatGateways.
 */
export interface LookupNatGatewaysResult {
    readonly ids?: string[];
    readonly nameRegex?: string;
    readonly natGateways: outputs.vpc.LookupNatGatewaysNatGateway[];
    readonly outputFile?: string;
    readonly totalCount: number;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
