// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ucloud.Ulb
{
    public static class GetLBRules
    {
        /// <summary>
        /// This data source provides a list of Load Balancer Rule resources according to their Load Balancer Rule ID.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Ucloud = Pulumi.Ucloud;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var example = Output.Create(Ucloud.Ulb.GetLBRules.InvokeAsync(new Ucloud.Ulb.GetLBRulesArgs
        ///         {
        ///             LoadBalancerId = "ulb-xxx",
        ///             ListenerId = "vserver-xxx",
        ///         }));
        ///         this.First = example.Apply(example =&gt; example.LbRules[0].Id);
        ///     }
        /// 
        ///     [Output("first")]
        ///     public Output&lt;string&gt; First { get; set; }
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetLBRulesResult> InvokeAsync(GetLBRulesArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetLBRulesResult>("ucloud:ulb/getLBRules:getLBRules", args ?? new GetLBRulesArgs(), options.WithVersion());
    }


    public sealed class GetLBRulesArgs : Pulumi.InvokeArgs
    {
        [Input("ids")]
        private List<string>? _ids;

        /// <summary>
        /// A list of LB Rule IDs, all the LB Rules belong to the Load Balancer listener will be retrieved if the ID is `[]`.
        /// </summary>
        public List<string> Ids
        {
            get => _ids ?? (_ids = new List<string>());
            set => _ids = value;
        }

        /// <summary>
        /// The ID of a listener server.
        /// </summary>
        [Input("listenerId", required: true)]
        public string ListenerId { get; set; } = null!;

        /// <summary>
        /// The ID of a load balancer.
        /// </summary>
        [Input("loadBalancerId", required: true)]
        public string LoadBalancerId { get; set; } = null!;

        [Input("outputFile")]
        public string? OutputFile { get; set; }

        public GetLBRulesArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetLBRulesResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> Ids;
        /// <summary>
        /// It is a nested type which documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetLBRulesLbRuleResult> LbRules;
        public readonly string ListenerId;
        public readonly string LoadBalancerId;
        public readonly string? OutputFile;
        /// <summary>
        /// Total number of LB Rules that satisfy the condition.
        /// </summary>
        public readonly int TotalCount;

        [OutputConstructor]
        private GetLBRulesResult(
            string id,

            ImmutableArray<string> ids,

            ImmutableArray<Outputs.GetLBRulesLbRuleResult> lbRules,

            string listenerId,

            string loadBalancerId,

            string? outputFile,

            int totalCount)
        {
            Id = id;
            Ids = ids;
            LbRules = lbRules;
            ListenerId = listenerId;
            LoadBalancerId = loadBalancerId;
            OutputFile = outputFile;
            TotalCount = totalCount;
        }
    }
}
