# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_ucloud.config as config
    import pulumi_ucloud.ipsecvpn as ipsecvpn
    import pulumi_ucloud.uaccount as uaccount
    import pulumi_ucloud.udb as udb
    import pulumi_ucloud.udisk as udisk
    import pulumi_ucloud.udpn as udpn
    import pulumi_ucloud.uhost as uhost
    import pulumi_ucloud.ulb as ulb
    import pulumi_ucloud.umem as umem
    import pulumi_ucloud.unet as unet
    import pulumi_ucloud.vpc as vpc
else:
    config = _utilities.lazy_import('pulumi_ucloud.config')
    ipsecvpn = _utilities.lazy_import('pulumi_ucloud.ipsecvpn')
    uaccount = _utilities.lazy_import('pulumi_ucloud.uaccount')
    udb = _utilities.lazy_import('pulumi_ucloud.udb')
    udisk = _utilities.lazy_import('pulumi_ucloud.udisk')
    udpn = _utilities.lazy_import('pulumi_ucloud.udpn')
    uhost = _utilities.lazy_import('pulumi_ucloud.uhost')
    ulb = _utilities.lazy_import('pulumi_ucloud.ulb')
    umem = _utilities.lazy_import('pulumi_ucloud.umem')
    unet = _utilities.lazy_import('pulumi_ucloud.unet')
    vpc = _utilities.lazy_import('pulumi_ucloud.vpc')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "ucloud",
  "mod": "ipsecvpn/vPNConnection",
  "fqn": "pulumi_ucloud.ipsecvpn",
  "classes": {
   "ucloud:ipsecvpn/vPNConnection:VPNConnection": "VPNConnection"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "ipsecvpn/vPNCustomerGateway",
  "fqn": "pulumi_ucloud.ipsecvpn",
  "classes": {
   "ucloud:ipsecvpn/vPNCustomerGateway:VPNCustomerGateway": "VPNCustomerGateway"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "ipsecvpn/vPNGateway",
  "fqn": "pulumi_ucloud.ipsecvpn",
  "classes": {
   "ucloud:ipsecvpn/vPNGateway:VPNGateway": "VPNGateway"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "udb/dBInstance",
  "fqn": "pulumi_ucloud.udb",
  "classes": {
   "ucloud:udb/dBInstance:DBInstance": "DBInstance"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "udisk/disk",
  "fqn": "pulumi_ucloud.udisk",
  "classes": {
   "ucloud:udisk/disk:Disk": "Disk"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "udisk/diskAttachment",
  "fqn": "pulumi_ucloud.udisk",
  "classes": {
   "ucloud:udisk/diskAttachment:DiskAttachment": "DiskAttachment"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "udpn/uDPNConnection",
  "fqn": "pulumi_ucloud.udpn",
  "classes": {
   "ucloud:udpn/uDPNConnection:UDPNConnection": "UDPNConnection"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "uhost/instance",
  "fqn": "pulumi_ucloud.uhost",
  "classes": {
   "ucloud:uhost/instance:Instance": "Instance"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "uhost/isolationGroup",
  "fqn": "pulumi_ucloud.uhost",
  "classes": {
   "ucloud:uhost/isolationGroup:IsolationGroup": "IsolationGroup"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "ulb/lB",
  "fqn": "pulumi_ucloud.ulb",
  "classes": {
   "ucloud:ulb/lB:LB": "LB"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "ulb/lBAttachment",
  "fqn": "pulumi_ucloud.ulb",
  "classes": {
   "ucloud:ulb/lBAttachment:LBAttachment": "LBAttachment"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "ulb/lBListener",
  "fqn": "pulumi_ucloud.ulb",
  "classes": {
   "ucloud:ulb/lBListener:LBListener": "LBListener"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "ulb/lBRule",
  "fqn": "pulumi_ucloud.ulb",
  "classes": {
   "ucloud:ulb/lBRule:LBRule": "LBRule"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "ulb/lBSsl",
  "fqn": "pulumi_ucloud.ulb",
  "classes": {
   "ucloud:ulb/lBSsl:LBSsl": "LBSsl"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "ulb/lBSslAttachment",
  "fqn": "pulumi_ucloud.ulb",
  "classes": {
   "ucloud:ulb/lBSslAttachment:LBSslAttachment": "LBSslAttachment"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "umem/memcachedInstance",
  "fqn": "pulumi_ucloud.umem",
  "classes": {
   "ucloud:umem/memcachedInstance:MemcachedInstance": "MemcachedInstance"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "umem/redisInstance",
  "fqn": "pulumi_ucloud.umem",
  "classes": {
   "ucloud:umem/redisInstance:RedisInstance": "RedisInstance"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "unet/eIP",
  "fqn": "pulumi_ucloud.unet",
  "classes": {
   "ucloud:unet/eIP:EIP": "EIP"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "unet/eIPAssociation",
  "fqn": "pulumi_ucloud.unet",
  "classes": {
   "ucloud:unet/eIPAssociation:EIPAssociation": "EIPAssociation"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "unet/securityGroup",
  "fqn": "pulumi_ucloud.unet",
  "classes": {
   "ucloud:unet/securityGroup:SecurityGroup": "SecurityGroup"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "vpc/nATGateway",
  "fqn": "pulumi_ucloud.vpc",
  "classes": {
   "ucloud:vpc/nATGateway:NATGateway": "NATGateway"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "vpc/nATGatewayRule",
  "fqn": "pulumi_ucloud.vpc",
  "classes": {
   "ucloud:vpc/nATGatewayRule:NATGatewayRule": "NATGatewayRule"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "vpc/subnet",
  "fqn": "pulumi_ucloud.vpc",
  "classes": {
   "ucloud:vpc/subnet:Subnet": "Subnet"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "vpc/vIP",
  "fqn": "pulumi_ucloud.vpc",
  "classes": {
   "ucloud:vpc/vIP:VIP": "VIP"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "vpc/vPC",
  "fqn": "pulumi_ucloud.vpc",
  "classes": {
   "ucloud:vpc/vPC:VPC": "VPC"
  }
 },
 {
  "pkg": "ucloud",
  "mod": "vpc/vPCPeeringConnection",
  "fqn": "pulumi_ucloud.vpc",
  "classes": {
   "ucloud:vpc/vPCPeeringConnection:VPCPeeringConnection": "VPCPeeringConnection"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "ucloud",
  "token": "pulumi:providers:ucloud",
  "fqn": "pulumi_ucloud",
  "class": "Provider"
 }
]
"""
)
