// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ucloud.Ulb.Inputs
{

    public sealed class LBIpSetGetArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Type of Elastic IP routes.
        /// </summary>
        [Input("internetType")]
        public Input<string>? InternetType { get; set; }

        /// <summary>
        /// Elastic IP address.
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        public LBIpSetGetArgs()
        {
        }
    }
}
